const userErrorNames = {
  UN_AUTHORIZED: "UN_AUTHORIZED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_DOES_NOT_EXISTS: "EMAIL_DOES_NOT_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_REGISTRATION_FAILED: "USER_REGISTRATION_FAILED",
  USER_PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
};

export default userErrorNames;
