export const demoAvatars = [
  "Clementine",
  "Morty",
  "Rodion Raskolnikov",
  "Sam Solo",
  "Starcrasher",
  "Shack",
  "Desmond",
  "Snake Harrison",
  "Pandemonium",
  "Broomhilda",
  "Cosmo Blue",
  "Blue Meal Shake",
  "Cryptonaut",
  "Lancaster",
  "Maggot",
  "Matrix",
  "Hiro",
  "Mavericat",
  "Huxley",
  "Elton David-Black",
  "Katerina Zoo",
  "Bloomdalf",
  "Emma",
  "The Elephant's Cat",
  "Nigel Ziemssen",
  "Sir Henchard",
  "Philip Klaus",
  "Daniel Marlowe",
  "Joachim Molesworth",
  "Molly Deronda",
  "Protagonist",
  "Lancelot",
  "Pechorin Bloom",
  "Kim",
  "Kim Patel",
  "Lorelei",
  "Battle Wooster",
  "Horatius",
  "Rhett James",
  "Moby Dick",
  "James Bolling",
  "Binx Bond",
  "Patrick Gatsby",
  "Inigo Argo",
  "Jay Bateman",
  "Victor Montoya",
  "Angela Flagg",
  "Randall Zone",
  "Major Salt",
  "Milo Minderbender",
  "Major Machine",
  "Skeleto",
  "Heep Starr",
  "11th Monster",
  "Wunderlick",
  "Big Brother",
  "Gonlithli",
  "Ebenezer Dimmsdale",
  "Hester Vega",
  "Honey Bunny",
  "Vincent Plant",
  "Butch Wallace",
  "Marsellus Coolidge",
  "Tuco",
  "Angel Boy",
  "Pablo Grimes",
  "Bounty Hunter",
  "Agent Smith",
  "Oracle",
  "Apoc State",
  "Switch",
  "Choi",
  "Angel Eyes",
  "Spoon Eyes",
  "Papillon",
  "Snooze 11",
  "Projectionist",
  "Landlady",
  "Ned Ramirez",
  "Michael Shimada",
  "Sonny Zen",
  "Bruno Fox",
  "Joker",
  "Lucius Tattaglia",
  "Scareblow",
  "Sugar Crash",
  "Neurostatic",
  "Kambei Corleone",
  "Shichiroji Karatoza",
  "Kuninori Bun Lord",
  "Bun Pusher",
  "Etno",
  "Wiggly Corleone",
  "Magnetofon",
  "Hitpagadee",
  "Doge",
  "Doge Panda",
  "Doge Locamotiv",
  "Doge Bulls",
  "Doge Lavrinovich",
  "Weeberblitz",
  "Arkadion",
  "Ninesouls",
  "Psycat",
  "Indoqueen",
  "DoubleDanceDragon",
  "Kinestetic Moves",
  "Zen Flash",
  "Orbit Escape",
  "Sin Azucar",
  "Particle Machine",
  "Spanglinga",
  "Pandalion",
  "Music Razor",
  "Bugzilla",
  "Bugz Bunuel",
  "Satoshi",
  "Nakamoto",
  "МЦ ДРУИД",
  "Jekaterina",
  "Quito",
  "Buenos Aires",
  "Ouarzazate",
  "Bogota",
  "Essaouira",
  "Extremadura",
  "Guadalajara",
  "Aphex",
  "Squarepusher",
  "Orbital",
  "Mozart",
  "Tesla",
  "Linux",
  "Ki",
  "Eshkoshka",
  "Aphex Maiden",
  "Iron Twin",
];
